### ISSUE TITLE
praat hier verder in de comments

### ISSUE THREAD

**Issue by Svennetjeee** [DamianSauren/Examen2019-2020#4]

**Comment by DamianSauren** [comment]
Isgoeie

**Comment by DamianSauren** [comment]
Wat heb jij bij doelstellingen

**Comment by Svennetjeee** [comment]
die doe ik zometeen, dan laat ik je het gelijk weten

**Comment by DamianSauren** [comment]
Doe ook gelijk ff takenlijst als je die hebt

**Comment by Svennetjeee** [comment]
ben nu ff n kanker uitgebreide planning aan t gooien daarom duurt t wat langer

**Comment by DamianSauren** [comment]
k heb echt ff je hulp nodig man
risiso's, projectgrenzen en takenlijst

**Comment by Svennetjeee** [comment]
risico's: 
Onvoldoende beschikking over middelen (geld)
Projectleider heeft onvoldoende kennis van zaken
Geen duidelijk en compleet projectplan

**Comment by Svennetjeee** [comment]
projectgrenzen en takenlijst is ook het enigste wat ik nog moet, ga ik nu doen

**Comment by Gardevour** [comment]
Wejow. Jij hebt veel meer dan ik.
Tijd voor herkansing I guess

**Comment by Svennetjeee** [comment]
wie is Gardevour, en ik heb ook sws herkansing so yea

**Comment by Gardevour** [comment]
Ik ben Gardevour

**Comment by DamianSauren** [comment]
daan

**Comment by DamianSauren** [comment]
Projectgrenzen
•	Wel binnen het project
o	Bestellingen en reserveringen registratie systeem
o	Lijst voor barman en kok
o	Uitbreidbaarheid voor restaurants en voorraadbeheer
o	Menukaart en drankenlijst maken
o	Bon voor klant maken
•	Niet binnen het project
o	Voorraadbeheer 
Projectgrenzen
•	Wel binnen het project
o	Bestellingen en reserveringen registratie systeem
o	Lijst voor barman en kok
o	Uitbreidbaarheid voor restaurants en voorraadbeheer
o	Menukaart en drankenlijst maken
o	Bon voor klant maken
•	Niet binnen het project
o	Voorraadbeheer

**Comment by Svennetjeee** [comment]
ik denk dat de takenlijst gwn de planning zonder datums wordt

**Comment by DamianSauren** [comment]
k ga het inleveren

**Comment by Svennetjeee** [comment]
enne faggots, wat moeten jullie nog

**Comment by Gardevour** [comment]
Moet alle ontwerpen nog maken, fuuuuuck

**Comment by Svennetjeee** [comment]
toch zo gedaan in 5min in paint lol

**Comment by DamianSauren** [comment]
Maken jullie ook uitvoerschermen?

**Comment by Gardevour** [comment]
Je weet hoe nauw Hanzaplast op die shit kijkt.

**Comment by Gardevour** [comment]
Moet alle formulieren nog tbh

**Comment by Svennetjeee** [comment]
minimaal 1 lol

**Comment by DamianSauren** [comment]
k ben vrijwel klaar denk ik

**Comment by Gardevour** [comment]
Moet alleen bestellingen nog. Maar ik heb geen idee hoe ik dat aanpak.

**Comment by DamianSauren** [comment]
kijk mn pdf

**Comment by Gardevour** [comment]
Fakka, ga gewoon inleveren die troep van mij.
