### ISSUE TITLE
lets go 

### ISSUE THREAD

**Issue by Svennetjeee** [DamianSauren/Examen2019-2020#5]

**Comment by DamianSauren** [comment]
Kan ik een proces gegevens alsnog zetten bij vastgegeven
of iig om het op te slaan in de databass

**Comment by Svennetjeee** [comment]
ligt aan situatie denk k

**Comment by Gardevour** [comment]
Je kan een rondje lopen in mijn ERD... kuuuut

**Comment by DamianSauren** [comment]
hebben jullie een tabel voor tafel?
zit nogal te twijfelen of ik die nodig heb

**Comment by Svennetjeee** [comment]
ik niet

**Comment by DamianSauren** [comment]
ik moet reservering met bon koppelen
en ik heb in beide tafel staan, maar idk of ik daar een key fso van moet maken

**Comment by Svennetjeee** [comment]
ik moet ook alleen nog gebruiker en reservering er bij koppelen

**Comment by Svennetjeee** [comment]
hoe moet ik dat doeeeeeeen

**Comment by Svennetjeee** [comment]
of je doet ReserveringID van reserveringen linken in de BON tabel, dan kan je bij elke bon kijken of het een reservering was
lm dan werkt reservering aanmaken niet meer

**Comment by Gardevour** [comment]
Bon doe ik gewoon via de code behind, Wollah

**Comment by Svennetjeee** [comment]
oftewel geen bon in de normalisatie?

**Comment by Svennetjeee** [comment]
ik kan je word bestand niet openen damian

**Comment by Gardevour** [comment]
idd, geen bon in de normalisatie.
Damian zijn bestanden moet je waarschijnlijk eerst downloaden.

**Comment by DamianSauren** [comment]
ik maak wel ff een pdfje

**Comment by Svennetjeee** [comment]
ben echt gwn te zenuwachtig pik auwhoer

**Comment by Gardevour** [comment]
Ik ben al klaar, en Melissa is nog met het klassendiagram bezig.
Sws iets goed fout gedaan.

**Comment by DamianSauren** [comment]
k ben klaar

**Comment by DamianSauren** [comment]
Lukt het nog?
